### ISSUE TITLE
btkRBFInterpolationS2S issue

### ISSUE THREAD

**Issue by danwu-bme** [rousseau/fbrain#68]
Dear fbrain authors,

I am running the btk pipeline on my fetal brain diffusion MRI data but got stuck on the btkRBFInterpolationS2S step. It could resample the first few DWI images, but ran into a problem in the middle and output an error saying "Segmentation fault (core dumped)". There was also a warning message saying "no neighbors found in the search area. Forcing search."  before the error message. 

May I know what could be the reason? My fetal brain diffusion data was acquired at1.7x1.7mm in-plane resolution, 4mm thickness, and 30 diffusion directions. The last step btkGroupwiseS2SDistortionCorrection was successfully, but some of the DWI volumes were badly transformed.

I appreciate your help!

Bests,
Dan

**Comment by rousseau** [comment]
Hi,

The interpolation step is based on a nearest neighbour approach, meaning that there is a process to look for neighbours around each point to compute. In your specific case, it seems that this step is not working properly, meaning that there is no neighbours close enough to the point to be processed. This can be due to large motions during the acquisition.

**Comment by danwu-bme** [comment]
Got it. Thanks a lot!
